/**
 * Generated by scripts/workbook/import.mjs on 2026-09-24. Do not edit by hand.
 *
 * Source: GENERAL!TABLES, GENERAL!SERVICES, GENERAL!VESSELS
 *
 * To change any value here, change the workbook and run the import again:
 *   npm run import:workbook -- --general <file> --bookings <file>
 *
 * See docs/quote/workbook-audit.md for what the workbook contains and
 * docs/quote/pricing-model.md for how the priced values were recovered.
 */
import type { Port, Service, Vessel } from '@/types/quote';

export const ports: Port[] = [
  {
    "id": "abu-dhabi",
    "slug": "abu-dhabi",
    "name": "ABU DHABI",
    "displayName": "Abu Dhabi",
    "locode": "AEAUH",
    "country": "United Arab Emirates",
    "region": "Red Sea",
    "latitude": 24.45,
    "longitude": 54.3827,
    "teu": 7800000,
    "portClass": "B",
    "baseIndex": 110,
    "services": [
      "eurasia"
    ],
    "calls": [
      {
        "serviceId": "eurasia",
        "terminal": "Khalifa Port Container Terminal (KPCT)",
        "agency": "Sailportlogistics.com United Arab Emirates",
        "representative": "Fatima Al-Mazroui",
        "email": "abudhabi@sdglines.com",
        "timeInPortDays": 0.6666666666666666,
        "utcOffsetHours": 4
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "algiers",
    "slug": "algiers",
    "name": "ALGIERS",
    "displayName": "Algiers",
    "locode": "DZALG",
    "country": "Algeria",
    "region": "West Med",
    "latitude": 36.7528,
    "longitude": 3.0422,
    "teu": 1553000,
    "portClass": "C",
    "baseIndex": 120,
    "services": [
      "westmed"
    ],
    "calls": [
      {
        "serviceId": "westmed",
        "terminal": "Algiers Container Terminal",
        "agency": "Sailportlogistics.com Algeria",
        "representative": "Amina Saidi",
        "email": "argel@sdglines.com",
        "timeInPortDays": 0.4166666666666667,
        "utcOffsetHours": 1
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "antwerp",
    "slug": "antwerp",
    "name": "ANTWERP",
    "displayName": "Antwerp",
    "locode": "BEANR",
    "country": "Belgium",
    "region": "Northern Europe",
    "latitude": 51.2194,
    "longitude": 4.4025,
    "teu": 12020000,
    "portClass": "A",
    "baseIndex": 90,
    "services": [
      "eurasia"
    ],
    "calls": [
      {
        "serviceId": "eurasia",
        "terminal": "Antwerp Gateway Terminal (AGT)",
        "agency": "Sailportlogistics.com Belgium",
        "representative": "Sophie Van Damme",
        "email": "antwerp@sdglines.com",
        "timeInPortDays": 0.6666666666666666,
        "utcOffsetHours": 1
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "aqaba",
    "slug": "aqaba",
    "name": "AQABA",
    "displayName": "Aqaba",
    "locode": "JOAQJ",
    "country": "Jordan",
    "region": "Red Sea",
    "latitude": 29.526,
    "longitude": 35.0075,
    "teu": 1200000,
    "portClass": "C",
    "baseIndex": 110,
    "services": [
      "eurasia",
      "optimed"
    ],
    "calls": [
      {
        "serviceId": "eurasia",
        "terminal": "Aqaba Container Terminal (ACT)",
        "agency": "Sailportlogistics.com Jordan",
        "representative": "Yasmin Al-Khalidi",
        "email": "aqaba@sdglines.com",
        "timeInPortDays": 0.6666666666666666,
        "utcOffsetHours": 3
      },
      {
        "serviceId": "optimed",
        "terminal": "MLC MOS Terminals Aqaba",
        "agency": "Sailportlogistics.com Jordan",
        "representative": "Yasmin Al-Khalidi",
        "email": "aqaba@sdglines.com",
        "timeInPortDays": 0.25,
        "utcOffsetHours": 3
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "bar",
    "slug": "bar",
    "name": "BAR",
    "displayName": "Bar",
    "locode": "MEBAR",
    "country": "Montenegro",
    "region": "Adriatic",
    "latitude": 42.099444,
    "longitude": 19.074444,
    "teu": 750000,
    "portClass": "D",
    "baseIndex": 120,
    "services": [
      "eastmed"
    ],
    "calls": [
      {
        "serviceId": "eastmed",
        "terminal": "SDGTerminals",
        "agency": "Sailportlogistics.com Montenegro",
        "representative": "Dušan Mandic",
        "email": "bar@sdglines.com",
        "timeInPortDays": 0.25,
        "utcOffsetHours": 1
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "barcelona",
    "slug": "barcelona",
    "name": "BARCELONA",
    "displayName": "Barcelona",
    "locode": "ESBCN",
    "country": "Spain",
    "region": "West Med",
    "latitude": 41.3793,
    "longitude": 2.1885,
    "teu": 3500000,
    "portClass": "C",
    "baseIndex": 100,
    "services": [
      "eurasia",
      "optimed",
      "gimnesias"
    ],
    "calls": [
      {
        "serviceId": "eurasia",
        "terminal": "Barcelona Container Terminal (BCT)",
        "agency": "Sailportlogistics.com Barcelona",
        "representative": "Joan Mariné Rodríguez",
        "email": "barcelona@sdglines.com",
        "timeInPortDays": 0.6666666666666666,
        "utcOffsetHours": 1
      },
      {
        "serviceId": "optimed",
        "terminal": "MLC MOS Terminals Barcelona",
        "agency": "Sailportlogistics.com Barcelona",
        "representative": "Joan Mariné Rodríguez",
        "email": "barcelona@sdglines.com",
        "timeInPortDays": 0.20833333333333334,
        "utcOffsetHours": 1
      },
      {
        "serviceId": "gimnesias",
        "terminal": "SDGFerry",
        "agency": "Sailportlogistics.com Spain",
        "representative": "Joan Mariné Rodríguez",
        "email": "barcelona@sdglines.com",
        "timeInPortDays": 0.16666666666666666,
        "utcOffsetHours": 1
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "bari",
    "slug": "bari",
    "name": "BARI",
    "displayName": "Bari",
    "locode": "ITBRI",
    "country": "Italy",
    "region": "West Med",
    "latitude": 41.1171,
    "longitude": 16.8719,
    "teu": 82000,
    "portClass": "D",
    "baseIndex": 120,
    "services": [
      "eastmed"
    ],
    "calls": [
      {
        "serviceId": "eastmed",
        "terminal": "SDGTerminals",
        "agency": "Sailportlogistics.com Italy",
        "representative": "Michele Decaro",
        "email": "bari@sdglines.com",
        "timeInPortDays": 0.25,
        "utcOffsetHours": 1
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "beirut",
    "slug": "beirut",
    "name": "BEIRUT",
    "displayName": "Beirut",
    "locode": "LBBEY",
    "country": "Lebanon",
    "region": "East Med",
    "latitude": 33.8959,
    "longitude": 35.4789,
    "teu": 1229100,
    "portClass": "C",
    "baseIndex": 110,
    "services": [
      "optimed"
    ],
    "calls": [
      {
        "serviceId": "optimed",
        "terminal": "MLC MOS Terminals Beirut",
        "agency": "Sailportlogistics.com Lebanon",
        "representative": "Nadine Khoury",
        "email": "beirut@sdglines.com",
        "timeInPortDays": 0.25,
        "utcOffsetHours": 2
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "busan",
    "slug": "busan",
    "name": "BUSAN",
    "displayName": "Busan",
    "locode": "KRPUS",
    "country": "South Korea",
    "region": "Eastern Asia",
    "latitude": 35.1796,
    "longitude": 129.0756,
    "teu": 21000000,
    "portClass": "A",
    "baseIndex": 95,
    "services": [
      "eurasia"
    ],
    "calls": [
      {
        "serviceId": "eurasia",
        "terminal": "Busan New Container Terminal (BNCT)",
        "agency": "Sailportlogistics.com South Korea",
        "representative": "Min-Jun Kim",
        "email": "busan@sdglines.com",
        "timeInPortDays": 0.3333333333333333,
        "utcOffsetHours": 9
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "casablanca",
    "slug": "casablanca",
    "name": "CASABLANCA",
    "displayName": "Casablanca",
    "locode": "MACAS",
    "country": "Morocco",
    "region": "West Med",
    "latitude": 33.6136,
    "longitude": -7.6198,
    "teu": 350000,
    "portClass": "D",
    "baseIndex": 100,
    "services": [
      "westmed"
    ],
    "calls": [
      {
        "serviceId": "westmed",
        "terminal": "Nouveau Terminal Est",
        "agency": "Sailportlogistics.com Morocco",
        "representative": "Khalid El Amrani",
        "email": "casablanca@sdglines.com",
        "timeInPortDays": 0.20833333333333334,
        "utcOffsetHours": 1
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "civitavecchia",
    "slug": "civitavecchia",
    "name": "CIVITAVECCHIA",
    "displayName": "Civitavecchia",
    "locode": "ITCIV",
    "country": "Italy",
    "region": "West Med",
    "latitude": 42.0892,
    "longitude": 11.7915,
    "teu": 112000,
    "portClass": "D",
    "baseIndex": 110,
    "services": [
      "optimed"
    ],
    "calls": [
      {
        "serviceId": "optimed",
        "terminal": "MLC MOS Terminals Rome",
        "agency": "Sailportlogistics.com Italy",
        "representative": "Giuliano Amato",
        "email": "rome@sdglines.com",
        "timeInPortDays": 0.20833333333333334,
        "utcOffsetHours": 1
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "damietta",
    "slug": "damietta",
    "name": "DAMIETTA",
    "displayName": "Damietta",
    "locode": "EGDAM",
    "country": "Egypt",
    "region": "East Med",
    "latitude": 31.4198,
    "longitude": 31.8115,
    "teu": 3300000,
    "portClass": "C",
    "baseIndex": 115,
    "services": [
      "optimed"
    ],
    "calls": [
      {
        "serviceId": "optimed",
        "terminal": "MLC MOS Terminals Damietta",
        "agency": "Sailportlogistics.com Egypt",
        "representative": "Mahmoud Abdel-Moneim",
        "email": "damietta@sdglines.com",
        "timeInPortDays": 0.2916666666666667,
        "utcOffsetHours": 1
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "durres",
    "slug": "durres",
    "name": "DURRES",
    "displayName": "Durres",
    "locode": "ALDRZ",
    "country": "Albania",
    "region": "Adriatic",
    "latitude": 41.3167,
    "longitude": 19.45,
    "teu": 180000,
    "portClass": "D",
    "baseIndex": 120,
    "services": [
      "eastmed"
    ],
    "calls": [
      {
        "serviceId": "eastmed",
        "terminal": "SDGTerminals",
        "agency": "Sailportlogistics.com Albania",
        "representative": "Arben Krasniqi",
        "email": "durres@sdglines.com",
        "timeInPortDays": 0.25,
        "utcOffsetHours": 1
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "felixstowe",
    "slug": "felixstowe",
    "name": "FELIXSTOWE",
    "displayName": "Felixstowe",
    "locode": "GBFXT",
    "country": "United Kingdom",
    "region": "Northern Europe",
    "latitude": 51.9638,
    "longitude": 1.3519,
    "teu": 3700000,
    "portClass": "C",
    "baseIndex": 90,
    "services": [
      "eurasia"
    ],
    "calls": [
      {
        "serviceId": "eurasia",
        "terminal": "Felixstowe Container Terminal (FCT)",
        "agency": "Sailportlogistics.com UK",
        "representative": "Emily Smith",
        "email": "felixstowe@sdglines.com",
        "timeInPortDays": 0.6666666666666666,
        "utcOffsetHours": 1
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "genova",
    "slug": "genova",
    "name": "GENOVA",
    "displayName": "Genova",
    "locode": "ITGOA",
    "country": "Italy",
    "region": "West Med",
    "latitude": 44.4072,
    "longitude": 8.9339,
    "teu": 2557000,
    "portClass": "C",
    "baseIndex": 100,
    "services": [
      "westmed"
    ],
    "calls": [
      {
        "serviceId": "westmed",
        "terminal": "Terminal Traghetti",
        "agency": "Sailportlogistics.com Italy",
        "representative": "Giulia Bianchi",
        "email": "genoa@sdglines.com",
        "timeInPortDays": 0.20833333333333334,
        "utcOffsetHours": 1
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "hamburg",
    "slug": "hamburg",
    "name": "HAMBURG",
    "displayName": "Hamburg",
    "locode": "DEHAM",
    "country": "Germany",
    "region": "Northern Europe",
    "latitude": 53.5511,
    "longitude": 9.9937,
    "teu": 8715000,
    "portClass": "B",
    "baseIndex": 90,
    "services": [
      "eurasia"
    ],
    "calls": [
      {
        "serviceId": "eurasia",
        "terminal": "Hamburg Port and Logistics AG (HHLA)",
        "agency": "Sailportlogistics.com Germany",
        "representative": "Klaus Schmidt",
        "email": "hamburg@sdglines.com",
        "timeInPortDays": 0.6666666666666666,
        "utcOffsetHours": 1
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "izmir",
    "slug": "izmir",
    "name": "IZMIR",
    "displayName": "Izmir",
    "locode": "TRIZM",
    "country": "Turkey",
    "region": "East Med",
    "latitude": 38.457,
    "longitude": 27.15267,
    "teu": 1967946,
    "portClass": "C",
    "baseIndex": 110,
    "services": [
      "eastmed"
    ],
    "calls": [
      {
        "serviceId": "eastmed",
        "terminal": "SDGTerminals",
        "agency": "Sailportlogistics.com Turkey",
        "representative": "Arben Krasniqi",
        "email": "izmir@sdglines.com",
        "timeInPortDays": 0.25,
        "utcOffsetHours": 3
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "jeddah",
    "slug": "jeddah",
    "name": "JEDDAH",
    "displayName": "Jeddah",
    "locode": "SAJED",
    "country": "Saudi Arabia",
    "region": "Red Sea",
    "latitude": 21.4858,
    "longitude": 39.1925,
    "teu": 4883000,
    "portClass": "C",
    "baseIndex": 110,
    "services": [
      "eurasia"
    ],
    "calls": [
      {
        "serviceId": "eurasia",
        "terminal": "Red Sea Gateway Terminal (RSGT)",
        "agency": "Sailportlogistics.com Saudi Arabia",
        "representative": "Ahmed Al-Mansour",
        "email": "jeddad@sdglines.com",
        "timeInPortDays": 0.6666666666666666,
        "utcOffsetHours": 3
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "las-palmas",
    "slug": "las-palmas",
    "name": "LAS PALMAS",
    "displayName": "Las Palmas",
    "locode": "ESLPA",
    "country": "Spain",
    "region": "Atlantic",
    "latitude": 28.1317,
    "longitude": -15.43,
    "teu": 1053000,
    "portClass": "C",
    "baseIndex": 100,
    "services": [
      "westmed"
    ],
    "calls": [
      {
        "serviceId": "westmed",
        "terminal": "Dique Muelle Nelson Mandela",
        "agency": "Sailportlogistics.com Spain",
        "representative": "María García",
        "email": "laspalmas@sdglines.com",
        "timeInPortDays": 0.20833333333333334,
        "utcOffsetHours": 1
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "le-havre",
    "slug": "le-havre",
    "name": "LE HAVRE",
    "displayName": "Le Havre",
    "locode": "FRLEH",
    "country": "France",
    "region": "Atlantic",
    "latitude": 49.4944,
    "longitude": 0.1077,
    "teu": 3019000,
    "portClass": "C",
    "baseIndex": 100,
    "services": [
      "eurasia"
    ],
    "calls": [
      {
        "serviceId": "eurasia",
        "terminal": "Le Havre Container Terminal (LHCT)",
        "agency": "Sailportlogistics.com France",
        "representative": "Pierre Dubois",
        "email": "lehavre@sdglines.com",
        "timeInPortDays": 0.6666666666666666,
        "utcOffsetHours": 1
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "lisbon",
    "slug": "lisbon",
    "name": "LISBON",
    "displayName": "Lisbon",
    "locode": "PTLIS",
    "country": "Portugal",
    "region": "Atlantic",
    "latitude": 38.7028,
    "longitude": -9.196,
    "teu": 1200000,
    "portClass": "C",
    "baseIndex": 110,
    "services": [
      "westmed"
    ],
    "calls": [
      {
        "serviceId": "westmed",
        "terminal": "SDGTerminals",
        "agency": "Sailportlogistics.com Portugal",
        "representative": "João Santos",
        "email": "lisbon@sdglines.com",
        "timeInPortDays": 0.25,
        "utcOffsetHours": 0
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "marseille",
    "slug": "marseille",
    "name": "MARSEILLE",
    "displayName": "Marseille",
    "locode": "FRMRS",
    "country": "France",
    "region": "West Med",
    "latitude": 43.2965,
    "longitude": 5.3698,
    "teu": 1500000,
    "portClass": "C",
    "baseIndex": 105,
    "services": [
      "optimed"
    ],
    "calls": [
      {
        "serviceId": "optimed",
        "terminal": "MLC MOS Terminals Marseille",
        "agency": "Sailportlogistics.com France",
        "representative": "Jean-Luc Dupont",
        "email": "marseille@sdglines.com",
        "timeInPortDays": 0.20833333333333334,
        "utcOffsetHours": 1
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "misurata",
    "slug": "misurata",
    "name": "MISURATA",
    "displayName": "Misurata",
    "locode": "LYMRA",
    "country": "Libya",
    "region": "West Med",
    "latitude": 32.4003,
    "longitude": 15.1267,
    "teu": 213000,
    "portClass": "D",
    "baseIndex": 130,
    "services": [
      "westmed"
    ],
    "calls": [
      {
        "serviceId": "westmed",
        "terminal": "SDGTerminals",
        "agency": "Sailportlogistics.com Libia",
        "representative": "Mustafa al Trabelsi",
        "email": "misurata@sdglines.com",
        "timeInPortDays": 0.3333333333333333,
        "utcOffsetHours": 1
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "mumbai",
    "slug": "mumbai",
    "name": "MUMBAI",
    "displayName": "Mumbai",
    "locode": "INBOM",
    "country": "India",
    "region": "Southern Asia",
    "latitude": 18.9636,
    "longitude": 72.8258,
    "teu": 10000000,
    "portClass": "B",
    "baseIndex": 110,
    "services": [
      "eurasia"
    ],
    "calls": [
      {
        "serviceId": "eurasia",
        "terminal": "Jawaharlal Nehru Port Container Terminal (Nhava Sheva)",
        "agency": "Sailportlogistics.com India",
        "representative": "Rajesh Patel",
        "email": "mumbai@sdglines.com",
        "timeInPortDays": 0.6666666666666666,
        "utcOffsetHours": 5.5
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "nouakchott",
    "slug": "nouakchott",
    "name": "NOUAKCHOTT",
    "displayName": "Nouakchott",
    "locode": "MRNKC",
    "country": "Mauritania",
    "region": "Middle Africa",
    "latitude": 18.097,
    "longitude": -15.9915,
    "teu": 84000,
    "portClass": "D",
    "baseIndex": 130,
    "services": [
      "westmed"
    ],
    "calls": [
      {
        "serviceId": "westmed",
        "terminal": "Nouakchott Terminal",
        "agency": "Sailportlogistics.com Mauritania",
        "representative": "Mohamed Diop",
        "email": "nouakchott@sdglinescom",
        "timeInPortDays": 0.4166666666666667,
        "utcOffsetHours": 0
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "oran",
    "slug": "oran",
    "name": "ORAN",
    "displayName": "Oran",
    "locode": "DZORN",
    "country": "Algeria",
    "region": "West Med",
    "latitude": null,
    "longitude": null,
    "teu": 278342,
    "portClass": "D",
    "baseIndex": 130,
    "services": [
      "westmed"
    ],
    "calls": [
      {
        "serviceId": "westmed",
        "terminal": "Algiers Container Terminal",
        "agency": "Sailportlogistics.com Algeria",
        "representative": null,
        "email": "argel@sdglines.com",
        "timeInPortDays": 0.25,
        "utcOffsetHours": 1
      }
    ],
    "meta": {
      "source": "corrected",
      "status": "needs-review",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24",
      "note": "Coordinates are column-shifted in GENERAL!TABLES; both were dropped."
    }
  },
  {
    "id": "palermo",
    "slug": "palermo",
    "name": "PALERMO",
    "displayName": "Palermo",
    "locode": "ITPMO",
    "country": "Italy",
    "region": "West Med",
    "latitude": 38.1112,
    "longitude": 13.3549,
    "teu": 120000,
    "portClass": "D",
    "baseIndex": 110,
    "services": [
      "eurasia"
    ],
    "calls": [
      {
        "serviceId": "eurasia",
        "terminal": "Porto di Palermo - SDGN Italia",
        "agency": "Sailportlogistics.com Italy",
        "representative": "Giovanni Russo",
        "email": "palermo@sdglines.com",
        "timeInPortDays": 0.6666666666666666,
        "utcOffsetHours": 1
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "palma",
    "slug": "palma",
    "name": "PALMA",
    "displayName": "Palma",
    "locode": "ESPMI",
    "country": "Spain",
    "region": "West Med",
    "latitude": null,
    "longitude": null,
    "teu": 457449,
    "portClass": "D",
    "baseIndex": 100,
    "services": [
      "gimnesias"
    ],
    "calls": [
      {
        "serviceId": "gimnesias",
        "terminal": "SDGFerry",
        "agency": "Sailportlogistics.com Spain",
        "representative": "Joan Mariné Rodríguez",
        "email": "palma@sdglines.com",
        "timeInPortDays": 0.125,
        "utcOffsetHours": 1
      }
    ],
    "meta": {
      "source": "simulation-design",
      "status": "needs-review",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24",
      "note": "Class and base index supplied by the product owner on 2026-09-23. The workbook lists neither. Class follows the TEU band; the base index matches the other Spanish ports."
    }
  },
  {
    "id": "piraeus",
    "slug": "piraeus",
    "name": "PIRAEUS",
    "displayName": "Piraeus",
    "locode": "GRPIR",
    "country": "Greece",
    "region": "East Med",
    "latitude": 37.9417,
    "longitude": 23.6533,
    "teu": 5311810,
    "portClass": "B",
    "baseIndex": 100,
    "services": [
      "eastmed"
    ],
    "calls": [
      {
        "serviceId": "eastmed",
        "terminal": "SDGTerminals",
        "agency": "Sailportlogistics.com Greece",
        "representative": "Emre Yılmaz",
        "email": "pireus@sdglines.com",
        "timeInPortDays": 0.25,
        "utcOffsetHours": 2
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "port-said",
    "slug": "port-said",
    "name": "PORT SAID",
    "displayName": "Port Said",
    "locode": "EGPSD",
    "country": "Egypt",
    "region": "East Med",
    "latitude": 31.2656,
    "longitude": 32.3019,
    "teu": 4764583,
    "portClass": "C",
    "baseIndex": 115,
    "services": [
      "eastmed"
    ],
    "calls": [
      {
        "serviceId": "eastmed",
        "terminal": "SDGTerminals",
        "agency": "Sailportlogistics.com Egypt",
        "representative": "Mohamed Kamel",
        "email": "portsaid@sdglines.com",
        "timeInPortDays": 0.25,
        "utcOffsetHours": 2
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "rades",
    "slug": "rades",
    "name": "RADES",
    "displayName": "Rades",
    "locode": "TNRAD",
    "country": "Tunisia",
    "region": "West Med",
    "latitude": 36.7709,
    "longitude": 10.3285,
    "teu": 7900000,
    "portClass": "B",
    "baseIndex": 130,
    "services": [
      "optimed"
    ],
    "calls": [
      {
        "serviceId": "optimed",
        "terminal": "MLC MOS Terminals Rades",
        "agency": "Sailportlogistics.com Tunis",
        "representative": "Ahmed Ben Ali",
        "email": "rades@sdglines.com",
        "timeInPortDays": 0.2916666666666667,
        "utcOffsetHours": 1
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "rotterdam",
    "slug": "rotterdam",
    "name": "ROTTERDAM",
    "displayName": "Rotterdam",
    "locode": "NLRTM",
    "country": "Netherlands",
    "region": "Northern Europe",
    "latitude": 51.9225,
    "longitude": 4.47917,
    "teu": 15300000,
    "portClass": "A",
    "baseIndex": 90,
    "services": [
      "eurasia"
    ],
    "calls": [
      {
        "serviceId": "eurasia",
        "terminal": "Rotterdam World Gateway (RWG)",
        "agency": "Sailportlogistics.com Netherlands",
        "representative": "Pieter van den Berg",
        "email": "rotterdam@sdglines.com",
        "timeInPortDays": 0.6666666666666666,
        "utcOffsetHours": 1
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "salalah",
    "slug": "salalah",
    "name": "SALALAH",
    "displayName": "Salalah",
    "locode": "OMSSH",
    "country": "Oman",
    "region": "Red Sea",
    "latitude": 17.0151,
    "longitude": 54.0924,
    "teu": 4510000,
    "portClass": "C",
    "baseIndex": 120,
    "services": [
      "eurasia"
    ],
    "calls": [
      {
        "serviceId": "eurasia",
        "terminal": "SALALAH Port General Cargo and Container Terminal",
        "agency": "Sailportlogistics.com Oman",
        "representative": "Suleiman Al-Jabri",
        "email": "SALALAH@sdglines.com",
        "timeInPortDays": 0.6666666666666666,
        "utcOffsetHours": 4
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "tanger-med",
    "slug": "tanger-med",
    "name": "TANGER MED",
    "displayName": "Tanger Med",
    "locode": "MATNG",
    "country": "Morocco",
    "region": "West Med",
    "latitude": 35.88462,
    "longitude": -5.50072,
    "teu": 7174000,
    "portClass": "B",
    "baseIndex": 90,
    "services": [
      "westmed"
    ],
    "calls": [
      {
        "serviceId": "westmed",
        "terminal": "Tangier Med Ferry Terminal",
        "agency": "Sailportlogistics.com Morocco",
        "representative": "Fatima Benhima",
        "email": "tangermed@sdglines.com",
        "timeInPortDays": 0.20833333333333334,
        "utcOffsetHours": 1
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "valencia",
    "slug": "valencia",
    "name": "VALENCIA",
    "displayName": "Valencia",
    "locode": "ESVLC",
    "country": "Spain",
    "region": "West Med",
    "latitude": 39.4699,
    "longitude": -0.3753,
    "teu": 5604478,
    "portClass": "B",
    "baseIndex": 100,
    "services": [
      "optimed"
    ],
    "calls": [
      {
        "serviceId": "optimed",
        "terminal": "MLC MOS Terminals Valencia",
        "agency": "Sailportlogistics.com Valencia",
        "representative": "Borja Casado",
        "email": "valencia@sdglines.com",
        "timeInPortDays": 0.20833333333333334,
        "utcOffsetHours": 1
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "valletta",
    "slug": "valletta",
    "name": "VALLETTA",
    "displayName": "Valletta",
    "locode": "MTVAL",
    "country": "Malta",
    "region": "West Med",
    "latitude": 35.898,
    "longitude": 14.5147,
    "teu": 200000,
    "portClass": "D",
    "baseIndex": 115,
    "services": [
      "eastmed"
    ],
    "calls": [
      {
        "serviceId": "eastmed",
        "terminal": "SDGTerminals",
        "agency": "Sailportlogistics.com Malta",
        "representative": "Maria Attard",
        "email": "VALLETTA@sdglines.com",
        "timeInPortDays": 0.25,
        "utcOffsetHours": 1
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "yantian",
    "slug": "yantian",
    "name": "YANTIAN",
    "displayName": "Yantian",
    "locode": "CNYTN",
    "country": "China",
    "region": "Red Sea",
    "latitude": 22.5728,
    "longitude": 114.2689,
    "teu": 16000000,
    "portClass": "A",
    "baseIndex": 85,
    "services": [
      "eurasia"
    ],
    "calls": [
      {
        "serviceId": "eurasia",
        "terminal": "Yantian International Container Terminal (YICT)",
        "agency": "Sailportlogistics.com China",
        "representative": "Li Wei",
        "email": "yantian@sdglines.com",
        "timeInPortDays": 0.3333333333333333,
        "utcOffsetHours": 8
      }
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!TABLES",
      "lastReviewed": "2026-09-24"
    }
  }
];

export const services: Service[] = [
  {
    "id": "westmed",
    "slug": "westmed",
    "name": "Westmed",
    "displayName": "Westmed",
    "speedKnots": 18.133,
    "legs": [
      {
        "fromPortId": "barcelona",
        "toPortId": "tanger-med",
        "distanceNm": 539,
        "transitDays": 1.238534,
        "timeInPortDays": 0.5
      },
      {
        "fromPortId": "tanger-med",
        "toPortId": "las-palmas",
        "distanceNm": 678,
        "transitDays": 1.557933,
        "timeInPortDays": 0.5
      },
      {
        "fromPortId": "las-palmas",
        "toPortId": "nouakchott",
        "distanceNm": 744,
        "transitDays": 1.70959,
        "timeInPortDays": 0.625
      },
      {
        "fromPortId": "nouakchott",
        "toPortId": "casablanca",
        "distanceNm": 1236,
        "transitDays": 2.840126,
        "timeInPortDays": 0.5
      },
      {
        "fromPortId": "casablanca",
        "toPortId": "tanger-med",
        "distanceNm": 168,
        "transitDays": 0.386037,
        "timeInPortDays": 0.5
      },
      {
        "fromPortId": "tanger-med",
        "toPortId": "oran",
        "distanceNm": 150,
        "transitDays": 0.344675,
        "timeInPortDays": 0.5
      },
      {
        "fromPortId": "oran",
        "toPortId": "algiers",
        "distanceNm": 200,
        "transitDays": 0.459567,
        "timeInPortDays": 0.5
      },
      {
        "fromPortId": "algiers",
        "toPortId": "barcelona",
        "distanceNm": 279,
        "transitDays": 0.641096,
        "timeInPortDays": 1.5
      }
    ],
    "totalDistanceNm": 3994,
    "roundTripDays": 14.3,
    "vessels": [
      "halide-edib-ad-var",
      "nawal-el-saadawi"
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!SERVICES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "eastmed",
    "slug": "eastmed",
    "name": "Eastmed",
    "displayName": "Eastmed",
    "speedKnots": 17.925,
    "legs": [
      {
        "fromPortId": "barcelona",
        "toPortId": "genova",
        "distanceNm": 352,
        "transitDays": 0.818224,
        "timeInPortDays": 0.291667
      },
      {
        "fromPortId": "genova",
        "toPortId": "valletta",
        "distanceNm": 580,
        "transitDays": 1.34821,
        "timeInPortDays": 0.25
      },
      {
        "fromPortId": "valletta",
        "toPortId": "misurata",
        "distanceNm": 214,
        "transitDays": 0.497443,
        "timeInPortDays": 0.25
      },
      {
        "fromPortId": "misurata",
        "toPortId": "port-said",
        "distanceNm": 1037,
        "transitDays": 2.410507,
        "timeInPortDays": 0.25
      },
      {
        "fromPortId": "port-said",
        "toPortId": "izmir",
        "distanceNm": 929,
        "transitDays": 2.159461,
        "timeInPortDays": 0.25
      },
      {
        "fromPortId": "izmir",
        "toPortId": "piraeus",
        "distanceNm": 204,
        "transitDays": 0.474198,
        "timeInPortDays": 0.25
      },
      {
        "fromPortId": "piraeus",
        "toPortId": "durres",
        "distanceNm": 618,
        "transitDays": 1.436541,
        "timeInPortDays": 0.25
      },
      {
        "fromPortId": "durres",
        "toPortId": "bari",
        "distanceNm": 113,
        "transitDays": 0.262669,
        "timeInPortDays": 0.25
      },
      {
        "fromPortId": "bari",
        "toPortId": "bar",
        "distanceNm": 153,
        "transitDays": 0.355649,
        "timeInPortDays": 0.25
      },
      {
        "fromPortId": "bar",
        "toPortId": "valletta",
        "distanceNm": 534,
        "transitDays": 1.241283,
        "timeInPortDays": 0.25
      },
      {
        "fromPortId": "valletta",
        "toPortId": "barcelona",
        "distanceNm": 666,
        "transitDays": 1.548117,
        "timeInPortDays": 0.25
      }
    ],
    "totalDistanceNm": 5400,
    "roundTripDays": 15.34,
    "vessels": [
      "merce-rodoreda",
      "sappho"
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!SERVICES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "optimed",
    "slug": "optimed",
    "name": "Optimed",
    "displayName": "Optimed",
    "speedKnots": 16.862,
    "legs": [
      {
        "fromPortId": "valencia",
        "toPortId": "barcelona",
        "distanceNm": 203,
        "transitDays": 0.501621,
        "timeInPortDays": 0.333333
      },
      {
        "fromPortId": "barcelona",
        "toPortId": "marseille",
        "distanceNm": 193,
        "transitDays": 0.476911,
        "timeInPortDays": 0.333333
      },
      {
        "fromPortId": "marseille",
        "toPortId": "civitavecchia",
        "distanceNm": 360,
        "transitDays": 0.889574,
        "timeInPortDays": 0.333333
      },
      {
        "fromPortId": "civitavecchia",
        "toPortId": "rades",
        "distanceNm": 384,
        "transitDays": 0.948879,
        "timeInPortDays": 0.333333
      },
      {
        "fromPortId": "rades",
        "toPortId": "beirut",
        "distanceNm": 1412,
        "transitDays": 3.489108,
        "timeInPortDays": 0.333333
      },
      {
        "fromPortId": "beirut",
        "toPortId": "damietta",
        "distanceNm": 323,
        "transitDays": 0.798146,
        "timeInPortDays": 0.333333
      },
      {
        "fromPortId": "damietta",
        "toPortId": "aqaba",
        "distanceNm": 430,
        "transitDays": 1.062547,
        "timeInPortDays": 0.333333
      },
      {
        "fromPortId": "aqaba",
        "toPortId": "damietta",
        "distanceNm": 430,
        "transitDays": 1.062547,
        "timeInPortDays": 0.333333
      },
      {
        "fromPortId": "damietta",
        "toPortId": "beirut",
        "distanceNm": 323,
        "transitDays": 0.798146,
        "timeInPortDays": 0.333333
      },
      {
        "fromPortId": "beirut",
        "toPortId": "rades",
        "distanceNm": 1412,
        "transitDays": 3.489108,
        "timeInPortDays": 0.333333
      },
      {
        "fromPortId": "rades",
        "toPortId": "civitavecchia",
        "distanceNm": 384,
        "transitDays": 0.948879,
        "timeInPortDays": 0.333333
      },
      {
        "fromPortId": "civitavecchia",
        "toPortId": "marseille",
        "distanceNm": 360,
        "transitDays": 0.889574,
        "timeInPortDays": 0.333333
      },
      {
        "fromPortId": "marseille",
        "toPortId": "barcelona",
        "distanceNm": 193,
        "transitDays": 0.476911,
        "timeInPortDays": 0.333333
      },
      {
        "fromPortId": "barcelona",
        "toPortId": "valencia",
        "distanceNm": 203,
        "transitDays": 0.501621,
        "timeInPortDays": 0.333333
      }
    ],
    "totalDistanceNm": 6610,
    "roundTripDays": 21,
    "vessels": [
      "aglahonike-of-thessaly",
      "theano-of-crotone",
      "hagnodice-of-athens"
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!SERVICES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "eurasia",
    "slug": "eurasia",
    "name": "EurAsia",
    "displayName": "EurAsia",
    "speedKnots": 18.09,
    "legs": [
      {
        "fromPortId": "barcelona",
        "toPortId": "lisbon",
        "distanceNm": 814,
        "transitDays": 1.874306,
        "timeInPortDays": 0.25
      },
      {
        "fromPortId": "lisbon",
        "toPortId": "antwerp",
        "distanceNm": 1091,
        "transitDays": 2.5125,
        "timeInPortDays": 0.25
      },
      {
        "fromPortId": "antwerp",
        "toPortId": "rotterdam",
        "distanceNm": 144,
        "transitDays": 0.33125,
        "timeInPortDays": 0.25
      },
      {
        "fromPortId": "rotterdam",
        "toPortId": "hamburg",
        "distanceNm": 341,
        "transitDays": 0.785417,
        "timeInPortDays": 0.25
      },
      {
        "fromPortId": "hamburg",
        "toPortId": "felixstowe",
        "distanceNm": 412,
        "transitDays": 0.948611,
        "timeInPortDays": 0.25
      },
      {
        "fromPortId": "felixstowe",
        "toPortId": "le-havre",
        "distanceNm": 243,
        "transitDays": 0.559028,
        "timeInPortDays": 0.25
      },
      {
        "fromPortId": "le-havre",
        "toPortId": "lisbon",
        "distanceNm": 881,
        "transitDays": 2.029167,
        "timeInPortDays": 0.25
      },
      {
        "fromPortId": "lisbon",
        "toPortId": "tanger-med",
        "distanceNm": 356,
        "transitDays": 0.819444,
        "timeInPortDays": 0.25
      },
      {
        "fromPortId": "tanger-med",
        "toPortId": "aqaba",
        "distanceNm": 2328,
        "transitDays": 5.361806,
        "timeInPortDays": 0.25
      },
      {
        "fromPortId": "aqaba",
        "toPortId": "jeddah",
        "distanceNm": 571,
        "transitDays": 1.314583,
        "timeInPortDays": 0.25
      },
      {
        "fromPortId": "jeddah",
        "toPortId": "abu-dhabi",
        "distanceNm": 2452,
        "transitDays": 5.647222,
        "timeInPortDays": 0.25
      },
      {
        "fromPortId": "abu-dhabi",
        "toPortId": "mumbai",
        "distanceNm": 1416,
        "transitDays": 3.261111,
        "timeInPortDays": 0.25
      },
      {
        "fromPortId": "mumbai",
        "toPortId": "salalah",
        "distanceNm": 1143,
        "transitDays": 2.632639,
        "timeInPortDays": 0.25
      },
      {
        "fromPortId": "salalah",
        "toPortId": "yantian",
        "distanceNm": 3800,
        "transitDays": 8.752778,
        "timeInPortDays": 0.25
      },
      {
        "fromPortId": "yantian",
        "toPortId": "busan",
        "distanceNm": 1488,
        "transitDays": 3.427083,
        "timeInPortDays": 0.25
      },
      {
        "fromPortId": "busan",
        "toPortId": "aqaba",
        "distanceNm": 5153,
        "transitDays": 11.892361,
        "timeInPortDays": 0.25
      },
      {
        "fromPortId": "aqaba",
        "toPortId": "palermo",
        "distanceNm": 1670,
        "transitDays": 3.845833,
        "timeInPortDays": 0.25
      },
      {
        "fromPortId": "palermo",
        "toPortId": "barcelona",
        "distanceNm": 695,
        "transitDays": 1.600694,
        "timeInPortDays": 0.25
      }
    ],
    "totalDistanceNm": 24998,
    "roundTripDays": 62.1,
    "vessels": [
      "maria-goeppert-mayer",
      "rita-levi-montalcini",
      "gerty-cori",
      "dorothy-hodgkin",
      "carolina-herschel",
      "frances-allen"
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!SERVICES",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "gimnesias",
    "slug": "gimnesias",
    "name": "Gimnesias",
    "displayName": "Gimnesias",
    "speedKnots": 10.186,
    "legs": [
      {
        "fromPortId": "barcelona",
        "toPortId": "palma",
        "distanceNm": 163,
        "transitDays": 0.666765,
        "timeInPortDays": 0.333333
      },
      {
        "fromPortId": "palma",
        "toPortId": "barcelona",
        "distanceNm": 163,
        "transitDays": 0.666765,
        "timeInPortDays": 0.333333
      },
      {
        "fromPortId": "barcelona",
        "toPortId": "palma",
        "distanceNm": 163,
        "transitDays": 0.666765,
        "timeInPortDays": 0.333333
      },
      {
        "fromPortId": "palma",
        "toPortId": "barcelona",
        "distanceNm": 163,
        "transitDays": 0.666765,
        "timeInPortDays": 0.333333
      },
      {
        "fromPortId": "barcelona",
        "toPortId": "palma",
        "distanceNm": 163,
        "transitDays": 0.666765,
        "timeInPortDays": 0.333333
      },
      {
        "fromPortId": "palma",
        "toPortId": "barcelona",
        "distanceNm": 163,
        "transitDays": 0.666765,
        "timeInPortDays": 1.333333
      }
    ],
    "totalDistanceNm": 978,
    "roundTripDays": 7,
    "vessels": [
      "rosa-sensat"
    ],
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!SERVICES",
      "lastReviewed": "2026-09-24"
    }
  }
];

export const vessels: Vessel[] = [
  {
    "id": "maria-goeppert-mayer",
    "slug": "maria-goeppert-mayer",
    "name": "Maria Goeppert-Mayer",
    "speedKnots": 17.72,
    "timeInPortDays": 0.3333333333333333,
    "serviceId": "eurasia",
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!VESSELS",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "rita-levi-montalcini",
    "slug": "rita-levi-montalcini",
    "name": "Rita Levi-Montalcini",
    "speedKnots": 17.72,
    "timeInPortDays": 0.3333333333333333,
    "serviceId": "eurasia",
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!VESSELS",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "gerty-cori",
    "slug": "gerty-cori",
    "name": "Gerty Cori",
    "speedKnots": 17.72,
    "timeInPortDays": 0.3333333333333333,
    "serviceId": "eurasia",
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!VESSELS",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "dorothy-hodgkin",
    "slug": "dorothy-hodgkin",
    "name": "Dorothy Hodgkin",
    "speedKnots": 17.72,
    "timeInPortDays": 0.3333333333333333,
    "serviceId": "eurasia",
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!VESSELS",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "carolina-herschel",
    "slug": "carolina-herschel",
    "name": "Carolina Herschel",
    "speedKnots": 17.72,
    "timeInPortDays": 0.3333333333333333,
    "serviceId": "eurasia",
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!VESSELS",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "aglahonike-of-thessaly",
    "slug": "aglahonike-of-thessaly",
    "name": "Aglahonike Of Thessaly",
    "speedKnots": 16.69,
    "timeInPortDays": 0.16666666666666666,
    "serviceId": "optimed",
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!VESSELS",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "theano-of-crotone",
    "slug": "theano-of-crotone",
    "name": "Theano Of Crotone",
    "speedKnots": 16.69,
    "timeInPortDays": 0.16666666666666666,
    "serviceId": "optimed",
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!VESSELS",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "hagnodice-of-athens",
    "slug": "hagnodice-of-athens",
    "name": "Hagnodice Of Athens",
    "speedKnots": 16.69,
    "timeInPortDays": 0.16666666666666666,
    "serviceId": "optimed",
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!VESSELS",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "merce-rodoreda",
    "slug": "merce-rodoreda",
    "name": "Merce Rodoreda",
    "speedKnots": 18.793,
    "timeInPortDays": 0.16666666666666666,
    "serviceId": "eastmed",
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!VESSELS",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "sappho",
    "slug": "sappho",
    "name": "Sappho",
    "speedKnots": 18.793,
    "timeInPortDays": 0.16666666666666666,
    "serviceId": "eastmed",
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!VESSELS",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "halide-edib-ad-var",
    "slug": "halide-edib-ad-var",
    "name": "Halide Edib Adıvar",
    "speedKnots": 17.045,
    "timeInPortDays": 0.3125,
    "serviceId": "westmed",
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!VESSELS",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "nawal-el-saadawi",
    "slug": "nawal-el-saadawi",
    "name": "Nawal El Saadawi",
    "speedKnots": 17.045,
    "timeInPortDays": 0.3125,
    "serviceId": "westmed",
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!VESSELS",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "elsa-morante",
    "slug": "elsa-morante",
    "name": "Elsa Morante",
    "speedKnots": 18.793,
    "timeInPortDays": 0.16666666666666666,
    "serviceId": null,
    "meta": {
      "source": "workbook",
      "status": "needs-review",
      "sourceSheet": "GENERAL!VESSELS",
      "lastReviewed": "2026-09-24",
      "note": "The workbook assigns no service, so this vessel cannot be scheduled."
    }
  },
  {
    "id": "maria-veleda",
    "slug": "maria-veleda",
    "name": "Maria Veleda",
    "speedKnots": 18.793,
    "timeInPortDays": 0.16666666666666666,
    "serviceId": null,
    "meta": {
      "source": "workbook",
      "status": "needs-review",
      "sourceSheet": "GENERAL!VESSELS",
      "lastReviewed": "2026-09-24",
      "note": "The workbook assigns no service, so this vessel cannot be scheduled."
    }
  },
  {
    "id": "fatema-mernissi",
    "slug": "fatema-mernissi",
    "name": "Fatema Mernissi",
    "speedKnots": 18.793,
    "timeInPortDays": 0.16666666666666666,
    "serviceId": null,
    "meta": {
      "source": "workbook",
      "status": "needs-review",
      "sourceSheet": "GENERAL!VESSELS",
      "lastReviewed": "2026-09-24",
      "note": "The workbook assigns no service, so this vessel cannot be scheduled."
    }
  },
  {
    "id": "maimouna-helene-uld-hamidou",
    "slug": "maimouna-helene-uld-hamidou",
    "name": "Maimouna Helene Uld Hamidou",
    "speedKnots": 18.793,
    "timeInPortDays": 0.16666666666666666,
    "serviceId": null,
    "meta": {
      "source": "workbook",
      "status": "needs-review",
      "sourceSheet": "GENERAL!VESSELS",
      "lastReviewed": "2026-09-24",
      "note": "The workbook assigns no service, so this vessel cannot be scheduled."
    }
  },
  {
    "id": "frances-allen",
    "slug": "frances-allen",
    "name": "Frances Allen",
    "speedKnots": null,
    "timeInPortDays": null,
    "serviceId": "eurasia",
    "meta": {
      "source": "workbook",
      "status": "needs-review",
      "sourceSheet": "GENERAL!VESSELS",
      "lastReviewed": "2026-09-24",
      "note": "The workbook gives no service speed."
    }
  },
  {
    "id": "rosa-sensat",
    "slug": "rosa-sensat",
    "name": "Rosa Sensat",
    "speedKnots": 10.186,
    "timeInPortDays": 0.3333333333333333,
    "serviceId": "gimnesias",
    "meta": {
      "source": "workbook",
      "status": "verified",
      "sourceSheet": "GENERAL!VESSELS",
      "lastReviewed": "2026-09-24"
    }
  },
  {
    "id": "range-vessels",
    "slug": "range-vessels",
    "name": "RANGE VESSELS",
    "speedKnots": null,
    "timeInPortDays": null,
    "serviceId": null,
    "meta": {
      "source": "workbook",
      "status": "needs-review",
      "sourceSheet": "GENERAL!VESSELS",
      "lastReviewed": "2026-09-24",
      "note": "The workbook assigns no service, so this vessel cannot be scheduled."
    }
  }
];
